
---

- hosts: localhost
  connection: local
  become: true
  vars: 
   user: ashu

  tasks:
   - name: install packages
     package:
       name: 
        - dconf-editor
        - tmux
        - openssh-server
        - xrdp
        - python3-psutil
   
   - name: copy a wallpaper
     copy:
        src: files/wallpaper.jpg
        dest: /usr/share/backgrounds/wallpaper.jpg
        owner: root
        group: root

   - name: set wallpaper
     become_user: {{user}}
     dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/wallpaper.jpg'"

   - name: set wallpapaer position 
     become_user: {{user}}
     dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
   - name: disable remote encryption
     become_user: {{user}}
     dconf:
        key: "/org/gnome/desktop/remote-access/require-encryption"
        value: False
   - name: setting vnc password
     become_user: {{user}}
     dconf:
        key: "/org/gnome/desktop/remote-access/vnc-password"
        value: "1234"
        
