
---

- hosts: localhost
  connection: local
  become: true

  tasks:
   - name: install packages
     package:
       name: 
        - dconf-editor
        - tmux
        - openssh-server
        - xrdp
   
   - name: copy a wallpaper
     copy:
        src: files/wallpaper.jpg
        dest: /usr/share/backgrounds/wallpaper.jpg
        owner: root
        group: root

   - name: set wallpaper
     dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/wallpaper.jpg'"

   - name: set wallpapaer 
     dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
